version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendSAH
    container_name: frontendSAH
    ports:
      - "3110:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebSAH

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendSAH
    container_name: backendSAH
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8110:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebSAH

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebSAH
    container_name: webSAH
    ports:
      - "85:80" # si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebSAH

networks:
  redwebSAH:
    driver: bridge